/* DO NOT EDIT THIS FILE - it is machine generated */

#include <jni.h>
/* Header for class com_aicas_fischertechnik_driver_AicasTxtCommonJNIDriver */

#ifndef _Included_com_aicas_fischertechnik_driver_AicasTxtCommonJNIDriver
#define _Included_com_aicas_fischertechnik_driver_AicasTxtCommonJNIDriver
#ifdef __cplusplus
extern "C" {
#endif


/* Class:     com.aicas.fischertechnik.driver.AicasTxtCommonJNIDriver
 * Method:    initTxt
 * Signature: ()I */
#ifdef __cplusplus
  extern "C"
#endif
JNIEXPORT jint JNICALL Java_com_aicas_fischertechnik_driver_AicasTxtCommonJNIDriver_initTxt(JNIEnv *env, jobject t);


/* Class:     com.aicas.fischertechnik.driver.AicasTxtCommonJNIDriver
 * Method:    uninitTxt
 * Signature: ()I */
#ifdef __cplusplus
  extern "C"
#endif
JNIEXPORT jint JNICALL Java_com_aicas_fischertechnik_driver_AicasTxtCommonJNIDriver_uninitTxt(JNIEnv *env, jobject t);


/* Class:     com.aicas.fischertechnik.driver.AicasTxtCommonJNIDriver
 * Method:    rotateMotor
 * Signature: (IIII)I */
#ifdef __cplusplus
  extern "C"
#endif
JNIEXPORT jint JNICALL Java_com_aicas_fischertechnik_driver_AicasTxtCommonJNIDriver_rotateMotor(JNIEnv *env, jobject t,
		jint id, jint direction, jint speed, jint distance);

#ifdef __cplusplus
}
#endif
#endif
