/* DO NOT EDIT THIS FILE - it is machine generated */

#include <jni.h>
/* Header for class com_aicas_fischertechnik_AicasTxtCommonJNIDriver */

#ifndef _Included_com_aicas_fischertechnik_AicasTxtCommonJNIDriver
#define _Included_com_aicas_fischertechnik_AicasTxtCommonJNIDriver
#ifdef __cplusplus
extern "C" {
#endif


/* Class:     com.aicas.fischertechnik.AicasTxtCommonJNIDriver
 * Method:    initTxt
 * Signature: ()I */
#ifdef __cplusplus
  extern "C"
#endif
JNIEXPORT jint JNICALL Java_com_aicas_fischertechnik_AicasTxtCommonJNIDriver_initTxt(JNIEnv *env, jobject t);


/* Class:     com.aicas.fischertechnik.AicasTxtCommonJNIDriver
 * Method:    uninitTxt
 * Signature: ()I */
#ifdef __cplusplus
  extern "C"
#endif
JNIEXPORT jint JNICALL Java_com_aicas_fischertechnik_AicasTxtCommonJNIDriver_uninitTxt(JNIEnv *env, jobject t);


/* Class:     com.aicas.fischertechnik.AicasTxtCommonJNIDriver
 * Method:    rotateMotor
 * Signature: (IIII)I */
#ifdef __cplusplus
  extern "C"
#endif
JNIEXPORT jint JNICALL Java_com_aicas_fischertechnik_AicasTxtCommonJNIDriver_rotateMotor(JNIEnv *env, jobject t, jint v0, jint v1, jint v2, jint v3);

#ifdef __cplusplus
}
#endif
#endif
