/* DO NOT EDIT THIS FILE - it is machine generated */

#include <jni.h>
/* Header for class com_aicas_fischertechnik_driver_AicasTxtCommonJNIDriver */

#ifndef _Included_com_aicas_fischertechnik_driver_AicasTxtCommonJNIDriver
#define _Included_com_aicas_fischertechnik_driver_AicasTxtCommonJNIDriver
#ifdef __cplusplus
extern "C" {
#endif


/* Class:     com.aicas.fischertechnik.driver.AicasTxtCommonJNIDriver
 * Method:    rotateMotor
 * Signature: (IIII)V */
#ifdef __cplusplus
  extern "C"
#endif
JNIEXPORT void JNICALL Java_com_aicas_fischertechnik_driver_AicasTxtCommonJNIDriver_rotateMotor(JNIEnv *env, jobject t, jint v0, jint v1, jint v2, jint v3);

#ifdef __cplusplus
}
#endif
#endif
